package component:middleware;

world middleware {
    /*use wasi:http/types@0.2.0-rc-2023-11-10.{
        outgoing-request, request-options, future-incoming-response, error-code
    };
    */

    import wasi:http/outgoing-handler@0.2.0-rc-2023-11-10;
    export wasi:http/outgoing-handler@0.2.0-rc-2023-11-10;
    //export exec: func(request: outgoing-request, options: option<request-options>) -> result<future-incoming-response, error-code>;
}